<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ben Lawrence">

<title>Midterm2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Midterm2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Midterm2_files/libs/quarto-html/quarto.js"></script>
<script src="Midterm2_files/libs/quarto-html/popper.min.js"></script>
<script src="Midterm2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Midterm2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Midterm2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Midterm2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Midterm2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Midterm2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Midterm2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Midterm2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ben Lawrence </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="midterm-2" class="level2">
<h2 class="anchored" data-anchor-id="midterm-2">Midterm 2</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(plotly))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:plotly':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pROC' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Functions to quickly make diagnostics</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates basic scatter plots</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>gg_basic <span class="ot">&lt;-</span> <span class="cf">function</span>(data, x, y) {</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> {{x}}, <span class="at">y =</span> {{y}})) <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_point</span>()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(plot)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates a 2x2 grid of basic diagnostic plots of a lm object</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>lm_diag <span class="ot">&lt;-</span> <span class="cf">function</span>(lm_model) {</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">gg_basic</span>(lm_model<span class="sc">$</span>model, <span class="fu">fitted</span>(lm_model), <span class="fu">residuals</span>(lm_model)) <span class="sc">+</span> </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Fitted Values"</span>, <span class="at">y=</span><span class="st">"Residuals"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> <span class="fu">gg_basic</span>(lm_model<span class="sc">$</span>model, <span class="fu">fitted</span>(lm_model), <span class="fu">rstandard</span>(lm_model)) <span class="sc">+</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Fitted Values"</span>, <span class="at">y=</span><span class="st">"Standardized Residuals"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  p3 <span class="ot">&lt;-</span> <span class="fu">gg_basic</span>(lm_model<span class="sc">$</span>model, <span class="fu">fitted</span>(lm_model), <span class="fu">hatvalues</span>(lm_model)) <span class="sc">+</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Fitted Values"</span>, <span class="at">y=</span><span class="st">"Leverage"</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create QQ plot of standardized residuals</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lm_model<span class="sc">$</span>model, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">rstandard</span>(lm_model))) <span class="sc">+</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>        <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>        <span class="fu">stat_qq_line</span>(<span class="at">colour=</span><span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">x =</span><span class="st">"Theoretical Quantiles"</span>, <span class="at">y=</span><span class="st">"Sample Quantiles"</span>) <span class="sc">+</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggtitle</span>(<span class="st">"QQ Plot of Standardized Residuals"</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arrange all plots into a grid</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">grid.arrange</span>(p1, p2, p3, p4, <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">nrow=</span><span class="dv">2</span>))</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>1a) Create a variable age by adding 1.5 to rings and use age as the response varaible and all other variables (not including rings for predictors (additively), create a scatterplot matrix of the data and comment on the relationship among the varaibles</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>snails <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"seasnails.csv"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Create new variable age</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>age <span class="ot">&lt;-</span> snails<span class="sc">$</span>Rings <span class="sc">+</span> <span class="fl">1.5</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(snails)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sex Length Diameter Height Whole_weight Shucked_weight Viscera_weight
1   M  0.455    0.365  0.095       0.5140         0.2245         0.1010
2   M  0.350    0.265  0.090       0.2255         0.0995         0.0485
3   F  0.530    0.420  0.135       0.6770         0.2565         0.1415
4   M  0.440    0.365  0.125       0.5160         0.2155         0.1140
5   I  0.330    0.255  0.080       0.2050         0.0895         0.0395
6   I  0.425    0.300  0.095       0.3515         0.1410         0.0775
  Shell_weight Rings  age
1        0.150    15 16.5
2        0.070     7  8.5
3        0.210     9 10.5
4        0.155    10 11.5
5        0.055     7  8.5
6        0.120     8  9.5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(age <span class="sc">~</span> <span class="fu">factor</span>(Sex) <span class="sc">+</span> Length <span class="sc">+</span> Diameter <span class="sc">+</span> Height <span class="sc">+</span> Whole_weight </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>      <span class="sc">+</span> Shucked_weight <span class="sc">+</span> Viscera_weight <span class="sc">+</span> Shell_weight, <span class="at">data=</span>snails)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>None of the predictors appear to have a linear relationship with the response. The argument could be made that Length and Diameter have a roughly linear relationship, but the apparent fanning out of points leads me to believe these variables will need transformations as well to produce a valid MLR model.</p>
<p>1b)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#full model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lm_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">factor</span>(Sex) <span class="sc">+</span> Length <span class="sc">+</span> Diameter <span class="sc">+</span> Height <span class="sc">+</span> Whole_weight </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>      <span class="sc">+</span> Shucked_weight <span class="sc">+</span> Viscera_weight <span class="sc">+</span> Shell_weight, <span class="at">data=</span>snails)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ factor(Sex) + Length + Diameter + Height + 
    Whole_weight + Shucked_weight + Viscera_weight + Shell_weight, 
    data = snails)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.4800  -1.3053  -0.3428   0.8600  13.9426 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.39464    0.29157  18.502  &lt; 2e-16 ***
factor(Sex)I    -0.82488    0.10240  -8.056 1.02e-15 ***
factor(Sex)M     0.05772    0.08335   0.692    0.489    
Length          -0.45834    1.80912  -0.253    0.800    
Diameter        11.07510    2.22728   4.972 6.88e-07 ***
Height          10.76154    1.53620   7.005 2.86e-12 ***
Whole_weight     8.97544    0.72540  12.373  &lt; 2e-16 ***
Shucked_weight -19.78687    0.81735 -24.209  &lt; 2e-16 ***
Viscera_weight -10.58183    1.29375  -8.179 3.76e-16 ***
Shell_weight     8.74181    1.12473   7.772 9.64e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.194 on 4167 degrees of freedom
Multiple R-squared:  0.5379,    Adjusted R-squared:  0.5369 
F-statistic: 538.9 on 9 and 4167 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(lm_full, <span class="at">lambda=</span><span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.36</span>, <span class="sc">-</span><span class="fl">0.2</span>, <span class="at">by =</span> <span class="fl">0.05</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">powerTransform</span>(lm_full))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>bcPower Transformation to Normality 
   Est Power Rounded Pwr Wald Lwr Bnd Wald Upr Bnd
Y1   -0.2841       -0.33      -0.3519      -0.2163

Likelihood ratio test that transformation parameter is equal to 0
 (log transformation)
                           LRT df       pval
LR test, lambda = (0) 64.97565  1 7.7716e-16

Likelihood ratio test that no transformation is needed
                          LRT df       pval
LR test, lambda = (1) 1192.79  1 &lt; 2.22e-16</code></pre>
</div>
</div>
<p>The Box-Cox analysis indicates we are 95% confident t hat the value of <span class="math inline">\(\lambda\)</span> lies between <span class="math inline">\(-0.36\)</span> and <span class="math inline">\(-0.2\)</span>. For the sake of intuition I will take lambda to be -0.3 and so the transformation will be <span class="math inline">\(Y^{-0.3}=age^{-0.3}=\frac{1}{age^{0.3}}\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lm_transformed <span class="ot">&lt;-</span> <span class="fu">lm</span>((age)<span class="sc">^</span>(<span class="sc">-</span><span class="fl">0.3</span>) <span class="sc">~</span> <span class="fu">factor</span>(Sex) <span class="sc">+</span> Length <span class="sc">+</span> Diameter <span class="sc">+</span> Height <span class="sc">+</span> Whole_weight <span class="sc">+</span> Shucked_weight <span class="sc">+</span> Viscera_weight <span class="sc">+</span> Shell_weight, <span class="at">data=</span>snails)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_transformed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = (age)^(-0.3) ~ factor(Sex) + Length + Diameter + 
    Height + Whole_weight + Shucked_weight + Viscera_weight + 
    Shell_weight, data = snails)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.096702 -0.014254  0.001647  0.016382  0.159507 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     0.6054769  0.0033519 180.638  &lt; 2e-16 ***
factor(Sex)I    0.0117671  0.0011771   9.996  &lt; 2e-16 ***
factor(Sex)M   -0.0011528  0.0009582  -1.203 0.228990    
Length         -0.0736194  0.0207979  -3.540 0.000405 ***
Diameter       -0.1827264  0.0256051  -7.136 1.13e-12 ***
Height         -0.1522381  0.0176604  -8.620  &lt; 2e-16 ***
Whole_weight   -0.0720400  0.0083393  -8.639  &lt; 2e-16 ***
Shucked_weight  0.2026001  0.0093964  21.562  &lt; 2e-16 ***
Viscera_weight  0.1009271  0.0148731   6.786 1.32e-11 ***
Shell_weight   -0.0725527  0.0129301  -5.611 2.14e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02522 on 4167 degrees of freedom
Multiple R-squared:  0.6048,    Adjusted R-squared:  0.6039 
F-statistic: 708.5 on 9 and 4167 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>1c) I will use the step() function which uses Backwards Stepwise Selection to compare models according to their number of predictors and find the model with the lowest AIC criteria.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>lm_trimmed <span class="ot">&lt;-</span> <span class="fu">step</span>(lm_transformed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-30732.4
(age)^(-0.3) ~ factor(Sex) + Length + Diameter + Height + Whole_weight + 
    Shucked_weight + Viscera_weight + Shell_weight

                 Df Sum of Sq    RSS    AIC
&lt;none&gt;                        2.6513 -30732
- Length          1  0.007972 2.6592 -30722
- Shell_weight    1  0.020032 2.6713 -30703
- Viscera_weight  1  0.029298 2.6806 -30689
- Diameter        1  0.032402 2.6837 -30684
- Height          1  0.047280 2.6985 -30661
- Whole_weight    1  0.047480 2.6987 -30660
- factor(Sex)     2  0.093945 2.7452 -30591
- Shucked_weight  1  0.295792 2.9470 -30293</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_trimmed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = (age)^(-0.3) ~ factor(Sex) + Length + Diameter + 
    Height + Whole_weight + Shucked_weight + Viscera_weight + 
    Shell_weight, data = snails)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.096702 -0.014254  0.001647  0.016382  0.159507 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     0.6054769  0.0033519 180.638  &lt; 2e-16 ***
factor(Sex)I    0.0117671  0.0011771   9.996  &lt; 2e-16 ***
factor(Sex)M   -0.0011528  0.0009582  -1.203 0.228990    
Length         -0.0736194  0.0207979  -3.540 0.000405 ***
Diameter       -0.1827264  0.0256051  -7.136 1.13e-12 ***
Height         -0.1522381  0.0176604  -8.620  &lt; 2e-16 ***
Whole_weight   -0.0720400  0.0083393  -8.639  &lt; 2e-16 ***
Shucked_weight  0.2026001  0.0093964  21.562  &lt; 2e-16 ***
Viscera_weight  0.1009271  0.0148731   6.786 1.32e-11 ***
Shell_weight   -0.0725527  0.0129301  -5.611 2.14e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02522 on 4167 degrees of freedom
Multiple R-squared:  0.6048,    Adjusted R-squared:  0.6039 
F-statistic: 708.5 on 9 and 4167 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>1d)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plots of Residuals, Leverage, and QQ</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm_diag</span>(lm_trimmed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The residual plots seem to be skewed left, and exhibit a nonlinear pattern, calling into question the assumption of constant variance. Leverage seems fine, there are no high leverage points. Normality could be better, especially in the left side, but it does not obviously seem like a problem.</p>
<p>1e)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Sex =</span> <span class="st">"M"</span>, <span class="at">Length =</span> <span class="fl">0.5</span>, <span class="at">Diameter =</span> <span class="fl">0.41</span>, <span class="at">Height =</span> <span class="fl">0.15</span>, <span class="at">Whole_weight =</span> <span class="fl">0.8</span>, <span class="at">Shucked_weight =</span> <span class="fl">0.4</span>, <span class="at">Viscera_weight =</span> <span class="fl">0.2</span>, <span class="at">Shell_weight =</span> <span class="fl">0.25</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lm_trimmed, <span class="at">newdata =</span> new, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit       lwr      upr
1 0.4952161 0.4457032 0.544729</code></pre>
</div>
</div>
<p>The estimated age is then 0.49 years, or about 6 months.</p>
<p>2a)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>newss <span class="ot">&lt;-</span> snails <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">!=</span> <span class="st">"I"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">as.factor</span>(Sex))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(newss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sex Length Diameter Height Whole_weight Shucked_weight Viscera_weight
1   M  0.455    0.365  0.095       0.5140         0.2245         0.1010
2   M  0.350    0.265  0.090       0.2255         0.0995         0.0485
3   F  0.530    0.420  0.135       0.6770         0.2565         0.1415
4   M  0.440    0.365  0.125       0.5160         0.2155         0.1140
5   F  0.530    0.415  0.150       0.7775         0.2370         0.1415
6   F  0.545    0.425  0.125       0.7680         0.2940         0.1495
  Shell_weight Rings  age
1        0.150    15 16.5
2        0.070     7  8.5
3        0.210     9 10.5
4        0.155    10 11.5
5        0.330    20 21.5
6        0.260    16 17.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>glm_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(Sex <span class="sc">~</span> . <span class="sc">-</span>age, <span class="at">data=</span>newss, <span class="at">family=</span>binomial)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Sex ~ . - age, family = binomial, data = newss)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     2.8279641  0.4600693   6.147 7.91e-10 ***
Length         -1.5740453  2.0524821  -0.767 0.443142    
Diameter       -4.9831673  2.4428140  -2.040 0.041357 *  
Height         -3.5417197  2.0357480  -1.740 0.081901 .  
Whole_weight   -0.0684691  0.7407270  -0.092 0.926352    
Shucked_weight  3.0847598  0.8882072   3.473 0.000515 ***
Viscera_weight -2.1395809  1.2765763  -1.676 0.093732 .  
Shell_weight    0.6507724  1.1380812   0.572 0.567447    
Rings           0.0004068  0.0160289   0.025 0.979753    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3912.9  on 2834  degrees of freedom
Residual deviance: 3837.4  on 2826  degrees of freedom
AIC: 3855.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Age is, by definition, linearly related to Rings, so including both as predictors would lead to problems with multicollinearity in the model.</p>
<p>2b)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>glm_trimmed <span class="ot">&lt;-</span> <span class="fu">step</span>(glm_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3855.36
Sex ~ (Length + Diameter + Height + Whole_weight + Shucked_weight + 
    Viscera_weight + Shell_weight + Rings + age) - age

                 Df Deviance    AIC
- Rings           1   3837.4 3853.4
- Whole_weight    1   3837.4 3853.4
- Shell_weight    1   3837.7 3853.7
- Length          1   3837.9 3853.9
&lt;none&gt;                3837.4 3855.4
- Viscera_weight  1   3840.2 3856.2
- Height          1   3841.5 3857.5
- Diameter        1   3841.5 3857.5
- Shucked_weight  1   3849.5 3865.5

Step:  AIC=3853.36
Sex ~ Length + Diameter + Height + Whole_weight + Shucked_weight + 
    Viscera_weight + Shell_weight

                 Df Deviance    AIC
- Whole_weight    1   3837.4 3851.4
- Shell_weight    1   3837.7 3851.7
- Length          1   3837.9 3851.9
&lt;none&gt;                3837.4 3853.4
- Viscera_weight  1   3840.2 3854.2
- Height          1   3841.5 3855.5
- Diameter        1   3841.5 3855.5
- Shucked_weight  1   3851.3 3865.3

Step:  AIC=3851.37
Sex ~ Length + Diameter + Height + Shucked_weight + Viscera_weight + 
    Shell_weight

                 Df Deviance    AIC
- Length          1   3838.0 3850.0
- Shell_weight    1   3838.0 3850.0
&lt;none&gt;                3837.4 3851.4
- Height          1   3841.5 3853.5
- Diameter        1   3841.6 3853.6
- Viscera_weight  1   3842.1 3854.1
- Shucked_weight  1   3879.3 3891.3

Step:  AIC=3849.96
Sex ~ Diameter + Height + Shucked_weight + Viscera_weight + Shell_weight

                 Df Deviance    AIC
- Shell_weight    1   3838.7 3848.7
&lt;none&gt;                3838.0 3850.0
- Height          1   3842.1 3852.1
- Viscera_weight  1   3843.4 3853.4
- Diameter        1   3862.7 3872.7
- Shucked_weight  1   3879.5 3889.5

Step:  AIC=3848.66
Sex ~ Diameter + Height + Shucked_weight + Viscera_weight

                 Df Deviance    AIC
&lt;none&gt;                3838.7 3848.7
- Height          1   3842.2 3850.2
- Viscera_weight  1   3843.5 3851.5
- Diameter        1   3863.9 3871.9
- Shucked_weight  1   3880.5 3888.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_trimmed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Sex ~ Diameter + Height + Shucked_weight + Viscera_weight, 
    family = binomial, data = newss)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      2.5412     0.3600   7.060 1.67e-12 ***
Diameter        -6.1177     1.2196  -5.016 5.27e-07 ***
Height          -3.0339     1.8311  -1.657   0.0975 .  
Shucked_weight   2.9561     0.4659   6.345 2.22e-10 ***
Viscera_weight  -2.1461     0.9780  -2.194   0.0282 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3912.9  on 2834  degrees of freedom
Residual deviance: 3838.7  on 2830  degrees of freedom
AIC: 3848.7

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><span class="math display">\[
\rm log\left(\frac{p(x)}{1-p(x)}\right)=\beta_0+\beta_1x+\cdots+\beta_px_p
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newss, <span class="fu">aes</span>(Shucked_weight, Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), <span class="at">se=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: algorithm did not converge</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Computation failed in `stat_smooth()`
Caused by error:
! y values must be 0 &lt;= y &lt;= 1</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Midterm2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the predictor Shucked_weight, the sign tells me that as the shucked_weight increases the log odds of a snail being male will increase (assuming the order in the graph above matches 0 to 1). Conversely, the other predictors since they have negative signs I predict an increase in their values will lead to an increase in the log odds of a snail being female.</p>
<p>2c)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>log_new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Length =</span> <span class="fl">0.5</span>, <span class="at">Diameter =</span> <span class="fl">0.41</span>, <span class="at">Height =</span> <span class="fl">0.15</span>, <span class="at">Whole_weight =</span> <span class="fl">0.8</span>, <span class="at">Shucked_weight =</span> <span class="fl">0.4</span>, <span class="at">Viscera_weight =</span> <span class="fl">0.2</span>, <span class="at">Shell_weight =</span> <span class="fl">0.25</span>, <span class="at">Rings =</span> <span class="dv">9</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(glm_trimmed, <span class="at">newdata =</span> log_new, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.3310529 </code></pre>
</div>
</div>
<p>The estimated probability of a snail being male is approximately 33.1%.</p>
<p>2d)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(roc_obj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>No documentation for 'roc_obj' in specified packages and libraries:
you could try '??roc_obj'</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm_trimmed, <span class="at">newdata =</span> newss, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(newss<span class="sc">$</span>Sex, probs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = F, case = M</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span> <span class="sc">-</span> roc_obj<span class="sc">$</span>specificities, roc_obj<span class="sc">$</span>sensitivities, <span class="at">type=</span><span class="st">"l"</span>,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"1 - Specificity"</span>, <span class="at">ylab =</span> <span class="st">"Sensitivity"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_obj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.5816</code></pre>
</div>
</div>
<p>The ROC curve is not skewed much to the upper left, meaning our model is not much better at classifying than simply guessing. This is further supported by the AUC which is very close to 0.5 (0.5816). So our model is slightly better than just guessing, but not by much.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>